### PR TITLE
Add support for SML files

### PR DESCRIPTION
**Pull request by dejarno**
SME files were not working for me
Hence I've added basic support for SML files
This fixes issue #1

### CODE REVIEW

**Comment by nradov** [comment]
Thanks for creating this PR. I don't really have time to work on this project right now but I added you as a collaborator on the repository so you should be able to merge it yourself.

**Comment by dejarno** [comment]
Hi @nradov, I was on a holiday and the invite expired, could you send it again or merge this PR? Thanks!

**Comment by nradov** [comment]
I sent another invitation.

**Comment by Checo18Ch** [comment]
I'm not a coder or a user of GitHub. in any case wondering if there was an update to the code to allow SML files to be used?

really having so many dives on my suunto that i would like to transfer accross to my new garmin.
thanks

**Pull request merged**
